In [ ]:
import pandas as pd
import numpy as np

In [1]:
import numpy as np

# Create a 5x5 identity matrix
two_dimensional_array = np.eye(5)

print(two_dimensional_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [2]:
import numpy as np

# Create a 4x4 diagonal matrix with specified values
two_dimensional_array = np.diag([1, 2, 3, 4])

print(two_dimensional_array)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [3]:

# Set the size of the checkerboard
rows, cols = 8, 8

# Create an empty array
checkerboard = np.zeros((rows, cols), dtype=int)

# Use slicing to set alternating values
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:

# Create an array of numbers from 1 to 10
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Compute the number of bytes occupied in memory
bytes_occupied = arr.nbytes

print(f"Number of bytes occupied in memory: {bytes_occupied} bytes")

Number of bytes occupied in memory: 40 bytes


In [5]:
# Given image snapshot
img = np.array([[200, 210, 209],
                [213, 0, 214],
                [214, 215, 217]])

# Calculate mean and median values
mean_value = np.mean(img)
median_value = np.median(img)

# Extract the center pixel value
center_pixel_value = img[1, 1]

print(f"Mean value: {mean_value}")
print(f"Median value: {median_value}")
print(f"Center pixel value: {center_pixel_value}")

Mean value: 188.0
Median value: 213.0
Center pixel value: 0


In [7]:
import pandas as pd
# Create a Pandas Series with student marks
marks = pd.Series([85, 92, 45, 60, 75, 88, 70, 95, 50])

# Filter marks based on conditions
marks_above_50 = marks[marks > 50]
marks_above_70 = marks[marks > 70]
marks_above_90 = marks[marks > 90]

# Display the results
print("Original marks:")
print(marks)
print("\nMarks > 50:")
print(marks_above_50)
print("\nMarks > 70:")
print(marks_above_70)
print("\nMarks > 90:")
print(marks_above_90)

Original marks:
0    85
1    92
2    45
3    60
4    75
5    88
6    70
7    95
8    50
dtype: int64

Marks > 50:
0    85
1    92
3    60
4    75
5    88
6    70
7    95
dtype: int64

Marks > 70:
0    85
1    92
4    75
5    88
7    95
dtype: int64

Marks > 90:
1    92
7    95
dtype: int64


In [8]:
student_names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
student_scores = np.array([85, 92, 78, 65])
student_grades = np.array(['A', 'A', 'B', 'C'])

# Create a data frame
student_df = pd.DataFrame({
    'Name': student_names,
    'Score': student_scores,
    'Grade': student_grades
})

# Display the data frame
print(student_df)

      Name  Score Grade
0    Alice     85     A
1      Bob     92     A
2  Charlie     78     B
3    David     65     C


In [ ]:
name=np.array(['kevin','john','hari'])
age=np.array([23,21,22])
gender=np.array(['m','m','f'])
state=np.array(['TN','KL','KN'])
cgpa=np.array([9,8,7])

age gender state  cgpa
kevin   23      m    TN     9
john    21      m    KL     8
hari    22      f    KN     7

In [11]:

# Given data in NumPy arrays
name = np.array(['kevin', 'john', 'hari'])
age = np.array([23, 21, 22])
gender = np.array(['m', 'm', 'f'])
state = np.array(['TN', 'KL', 'KN'])
cgpa = np.array([9, 8, 7])

# Create a Pandas DataFrame
df = pd.DataFrame({
    'Name': name,
    'Age': age,
    'Gender': gender,
    'State': state,
    'CGPA': cgpa
})

# 1. Filter the age
age_filter = df['Age']

# 2. Filter age, cgpa
age_cgpa_filter = df[['Age', 'CGPA']]

# 3. Filter age > 22
age_above_22_filter = df[df['Age'] > 22]

# 4. Names starts with 'j'
names_starts_with_j = df[df['Name'].str.startswith('j')]

# 5. Names contain 'n'
names_contain_n = df[df['Name'].str.contains('n')]

# Display the results
print("Original DataFrame:")
print(df)
print("\n1. Filtered Age:")
print(age_filter)
print("\n2. Filtered Age and CGPA:")
print(age_cgpa_filter)
print("\n3. Filtered Age > 22:")
print(age_above_22_filter)
print("\n4. Names starts with 'j':")
print(names_starts_with_j)
print("\n5. Names contain 'n':")
print(names_contain_n)

Original DataFrame:
    Name  Age Gender State  CGPA
0  kevin   23      m    TN     9
1   john   21      m    KL     8
2   hari   22      f    KN     7

1. Filtered Age:
0    23
1    21
2    22
Name: Age, dtype: int32

2. Filtered Age and CGPA:
   Age  CGPA
0   23     9
1   21     8
2   22     7

3. Filtered Age > 22:
    Name  Age Gender State  CGPA
0  kevin   23      m    TN     9

4. Names starts with 'j':
   Name  Age Gender State  CGPA
1  john   21      m    KL     8

5. Names contain 'n':
    Name  Age Gender State  CGPA
0  kevin   23      m    TN     9
1   john   21      m    KL     8


In [12]:
import pandas as pd

# Given dataframes
dfr1 = pd.DataFrame({'Id':[1,2,3,5,9],
                    'Col1':[1,2,3,4,5],
                    'col2':[6,7,8,9,10],
                    'col4':['apple','orange','banana','strawberry','raspberry']})

dfr2 = pd.DataFrame({'Id':[1,1,3,5],
                    'ColA':[8,9,10,11],
                    'colB':[12,13,15,17],
                    'col4':['apple','orange','banana','kiwi']})

# Perform left join
left_join = pd.merge(dfr1, dfr2, on='Id', how='left', suffixes=('_dfr1', '_dfr2'))

# Perform right join
right_join = pd.merge(dfr1, dfr2, on='Id', how='right', suffixes=('_dfr1', '_dfr2'))

# Perform inner join
inner_join = pd.merge(dfr1, dfr2, on='Id', how='inner', suffixes=('_dfr1', '_dfr2'))

# Display the results
print("Left Join:")
print(left_join)

print("\nRight Join:")
print(right_join)

print("\nInner Join:")
print(inner_join)


Left Join:
   Id  Col1  col2   col4_dfr1  ColA  colB col4_dfr2
0   1     1     6       apple   8.0  12.0     apple
1   1     1     6       apple   9.0  13.0    orange
2   2     2     7      orange   NaN   NaN       NaN
3   3     3     8      banana  10.0  15.0    banana
4   5     4     9  strawberry  11.0  17.0      kiwi
5   9     5    10   raspberry   NaN   NaN       NaN

Right Join:
   Id  Col1  col2   col4_dfr1  ColA  colB col4_dfr2
0   1     1     6       apple     8    12     apple
1   1     1     6       apple     9    13    orange
2   3     3     8      banana    10    15    banana
3   5     4     9  strawberry    11    17      kiwi

Inner Join:
   Id  Col1  col2   col4_dfr1  ColA  colB col4_dfr2
0   1     1     6       apple     8    12     apple
1   1     1     6       apple     9    13    orange
2   3     3     8      banana    10    15    banana
3   5     4     9  strawberry    11    17      kiwi


In [13]:
import numpy as np

# 1. Define sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# 2. Create the NumPy array
input_array = np.array([2, 5, 6])

# 3. Apply the sigmoid function to the array
result = sigmoid(input_array)

# Display the results
print("Original Array:", input_array)
print("Result after applying sigmoid function:", result)

Original Array: [2 5 6]
Result after applying sigmoid function: [0.88079708 0.99330715 0.99752738]
